name: Build workflow

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode package
      - name: action-zip
        uses: montudor/action-zip@v1.0.0
      - name: Create Release Artifact
        run: mkdir dist && cp -R target/lib dist/ && cp target/radix-*.jar dist/ && cd dist && zip -r ../radix-address-generator.zip .
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@v2.1.0
        with:
          args: ./radix-address-generator.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
